// <auto-generated />
using System;
using BeerOverflow.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeerOverflow.Database.Migrations
{
    [DbContext(typeof(BeerOverflowContext))]
    partial class BeerOverflowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeerOverflow.Models.Beer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AlcoholByVolume")
                        .HasColumnType("float");

                    b.Property<int>("BreweryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreweryId");

                    b.HasIndex("TypeId");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlcoholByVolume = 4.5,
                            BreweryId = 1,
                            CreatedOn = new DateTime(2020, 4, 15, 13, 10, 48, 600, DateTimeKind.Local).AddTicks(9101),
                            IsDeleted = false,
                            Likes = 40,
                            Name = "Ot Na Pesho Zadniq Dvor Birata",
                            TypeId = 1
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.BeerDrank", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "BeerId");

                    b.HasIndex("BeerId");

                    b.ToTable("BeersDrank");
                });

            modelBuilder.Entity("BeerOverflow.Models.BeerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("BeerType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PaleAle"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.Brewery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Breweries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            CreatedOn = new DateTime(2020, 4, 15, 13, 10, 48, 598, DateTimeKind.Local).AddTicks(6519),
                            IsDeleted = false,
                            Name = "Na Pesho Zadniq Dvor"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "AX",
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 5,
                            CountryCode = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 6,
                            CountryCode = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 7,
                            CountryCode = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 8,
                            CountryCode = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 9,
                            CountryCode = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 10,
                            CountryCode = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 11,
                            CountryCode = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 12,
                            CountryCode = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 13,
                            CountryCode = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 14,
                            CountryCode = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 15,
                            CountryCode = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 16,
                            CountryCode = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 17,
                            CountryCode = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 18,
                            CountryCode = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 19,
                            CountryCode = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 20,
                            CountryCode = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 21,
                            CountryCode = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 22,
                            CountryCode = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 23,
                            CountryCode = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 24,
                            CountryCode = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 25,
                            CountryCode = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 26,
                            CountryCode = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 27,
                            CountryCode = "BQ",
                            Name = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            Id = 28,
                            CountryCode = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 29,
                            CountryCode = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 30,
                            CountryCode = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 31,
                            CountryCode = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 32,
                            CountryCode = "VG",
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Id = 33,
                            CountryCode = "BN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 34,
                            CountryCode = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 35,
                            CountryCode = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 36,
                            CountryCode = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 37,
                            CountryCode = "CV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 38,
                            CountryCode = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 39,
                            CountryCode = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 40,
                            CountryCode = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 41,
                            CountryCode = "029",
                            Name = "Caribbean"
                        },
                        new
                        {
                            Id = 42,
                            CountryCode = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 43,
                            CountryCode = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 44,
                            CountryCode = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 45,
                            CountryCode = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 46,
                            CountryCode = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 47,
                            CountryCode = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 48,
                            CountryCode = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 49,
                            CountryCode = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 50,
                            CountryCode = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 51,
                            CountryCode = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 52,
                            CountryCode = "CD",
                            Name = "Congo (DRC)"
                        },
                        new
                        {
                            Id = 53,
                            CountryCode = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 54,
                            CountryCode = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 55,
                            CountryCode = "CI",
                            Name = "Côte d’Ivoire"
                        },
                        new
                        {
                            Id = 56,
                            CountryCode = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 57,
                            CountryCode = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 58,
                            CountryCode = "CW",
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = 59,
                            CountryCode = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 60,
                            CountryCode = "CZ",
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = 61,
                            CountryCode = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 62,
                            CountryCode = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 63,
                            CountryCode = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 64,
                            CountryCode = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 65,
                            CountryCode = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 66,
                            CountryCode = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 67,
                            CountryCode = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 68,
                            CountryCode = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 69,
                            CountryCode = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 70,
                            CountryCode = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 71,
                            CountryCode = "SZ",
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 72,
                            CountryCode = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 73,
                            CountryCode = "150",
                            Name = "Europe"
                        },
                        new
                        {
                            Id = 74,
                            CountryCode = "FK",
                            Name = "Falkland Islands"
                        },
                        new
                        {
                            Id = 75,
                            CountryCode = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 76,
                            CountryCode = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 77,
                            CountryCode = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 78,
                            CountryCode = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = 79,
                            CountryCode = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 80,
                            CountryCode = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 81,
                            CountryCode = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 82,
                            CountryCode = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 83,
                            CountryCode = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 84,
                            CountryCode = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 85,
                            CountryCode = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 86,
                            CountryCode = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 87,
                            CountryCode = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 88,
                            CountryCode = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 89,
                            CountryCode = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 90,
                            CountryCode = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 91,
                            CountryCode = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 92,
                            CountryCode = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 93,
                            CountryCode = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = 94,
                            CountryCode = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 95,
                            CountryCode = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 96,
                            CountryCode = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 97,
                            CountryCode = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 98,
                            CountryCode = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 99,
                            CountryCode = "HK",
                            Name = "Hong Kong SAR"
                        },
                        new
                        {
                            Id = 100,
                            CountryCode = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 101,
                            CountryCode = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 102,
                            CountryCode = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 103,
                            CountryCode = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 104,
                            CountryCode = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 105,
                            CountryCode = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 106,
                            CountryCode = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 107,
                            CountryCode = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = 108,
                            CountryCode = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 109,
                            CountryCode = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 110,
                            CountryCode = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 111,
                            CountryCode = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 112,
                            CountryCode = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 113,
                            CountryCode = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 114,
                            CountryCode = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 115,
                            CountryCode = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 116,
                            CountryCode = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 117,
                            CountryCode = "KR",
                            Name = "Korea"
                        },
                        new
                        {
                            Id = 118,
                            CountryCode = "XK",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = 119,
                            CountryCode = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 120,
                            CountryCode = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 121,
                            CountryCode = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 122,
                            CountryCode = "419",
                            Name = "Latin America"
                        },
                        new
                        {
                            Id = 123,
                            CountryCode = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 124,
                            CountryCode = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 125,
                            CountryCode = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 126,
                            CountryCode = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 127,
                            CountryCode = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 128,
                            CountryCode = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 129,
                            CountryCode = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 130,
                            CountryCode = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 131,
                            CountryCode = "MO",
                            Name = "Macao SAR"
                        },
                        new
                        {
                            Id = 132,
                            CountryCode = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 133,
                            CountryCode = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 134,
                            CountryCode = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 135,
                            CountryCode = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 136,
                            CountryCode = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 137,
                            CountryCode = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 138,
                            CountryCode = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 139,
                            CountryCode = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 140,
                            CountryCode = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 141,
                            CountryCode = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 142,
                            CountryCode = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 143,
                            CountryCode = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 144,
                            CountryCode = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 145,
                            CountryCode = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 146,
                            CountryCode = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 147,
                            CountryCode = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 148,
                            CountryCode = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 149,
                            CountryCode = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 150,
                            CountryCode = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 151,
                            CountryCode = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 152,
                            CountryCode = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 153,
                            CountryCode = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 154,
                            CountryCode = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 155,
                            CountryCode = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 156,
                            CountryCode = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 157,
                            CountryCode = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 158,
                            CountryCode = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 159,
                            CountryCode = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 160,
                            CountryCode = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 161,
                            CountryCode = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 162,
                            CountryCode = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 163,
                            CountryCode = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 164,
                            CountryCode = "KP",
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 165,
                            CountryCode = "MK",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 166,
                            CountryCode = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 167,
                            CountryCode = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 168,
                            CountryCode = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 169,
                            CountryCode = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 170,
                            CountryCode = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 171,
                            CountryCode = "PS",
                            Name = "Palestinian Authority"
                        },
                        new
                        {
                            Id = 172,
                            CountryCode = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 173,
                            CountryCode = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 174,
                            CountryCode = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 175,
                            CountryCode = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 176,
                            CountryCode = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 177,
                            CountryCode = "PN",
                            Name = "Pitcairn Islands"
                        },
                        new
                        {
                            Id = 178,
                            CountryCode = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 179,
                            CountryCode = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 180,
                            CountryCode = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 181,
                            CountryCode = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 182,
                            CountryCode = "RE",
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = 183,
                            CountryCode = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 184,
                            CountryCode = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 185,
                            CountryCode = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 186,
                            CountryCode = "BL",
                            Name = "Saint Barthélemy"
                        },
                        new
                        {
                            Id = 187,
                            CountryCode = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 188,
                            CountryCode = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 189,
                            CountryCode = "MF",
                            Name = "Saint Martin"
                        },
                        new
                        {
                            Id = 190,
                            CountryCode = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 191,
                            CountryCode = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 192,
                            CountryCode = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 193,
                            CountryCode = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 194,
                            CountryCode = "ST",
                            Name = "São Tomé and Príncipe"
                        },
                        new
                        {
                            Id = 195,
                            CountryCode = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 196,
                            CountryCode = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 197,
                            CountryCode = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 198,
                            CountryCode = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 199,
                            CountryCode = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 200,
                            CountryCode = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 201,
                            CountryCode = "SX",
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            Id = 202,
                            CountryCode = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 203,
                            CountryCode = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 204,
                            CountryCode = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 205,
                            CountryCode = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 206,
                            CountryCode = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 207,
                            CountryCode = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 208,
                            CountryCode = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 209,
                            CountryCode = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 210,
                            CountryCode = "SH",
                            Name = "St Helena, Ascension, Tristan da Cunha"
                        },
                        new
                        {
                            Id = 211,
                            CountryCode = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 212,
                            CountryCode = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 213,
                            CountryCode = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = 214,
                            CountryCode = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 215,
                            CountryCode = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 216,
                            CountryCode = "SY",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 217,
                            CountryCode = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 218,
                            CountryCode = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 219,
                            CountryCode = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 220,
                            CountryCode = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 221,
                            CountryCode = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 222,
                            CountryCode = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 223,
                            CountryCode = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 224,
                            CountryCode = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 225,
                            CountryCode = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 226,
                            CountryCode = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 227,
                            CountryCode = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 228,
                            CountryCode = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 229,
                            CountryCode = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 230,
                            CountryCode = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 231,
                            CountryCode = "UM",
                            Name = "U.S. Outlying Islands"
                        },
                        new
                        {
                            Id = 232,
                            CountryCode = "VI",
                            Name = "U.S. Virgin Islands"
                        },
                        new
                        {
                            Id = 233,
                            CountryCode = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 234,
                            CountryCode = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 235,
                            CountryCode = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 236,
                            CountryCode = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 237,
                            CountryCode = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 238,
                            CountryCode = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 239,
                            CountryCode = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 240,
                            CountryCode = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 241,
                            CountryCode = "VA",
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 242,
                            CountryCode = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 243,
                            CountryCode = "VN",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 244,
                            CountryCode = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 245,
                            CountryCode = "001",
                            Name = "World"
                        },
                        new
                        {
                            Id = 246,
                            CountryCode = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 247,
                            CountryCode = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 248,
                            CountryCode = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TargetBeerId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TargetBeerId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CreatedOn = new DateTime(2020, 4, 15, 13, 10, 48, 601, DateTimeKind.Local).AddTicks(8668),
                            IsDeleted = false,
                            Likes = 2,
                            Name = "Na Pesho Review-to",
                            Rating = 0,
                            TargetBeerId = 1,
                            Text = "Mnoo dobra bira brat"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BanReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 4, 15, 13, 10, 48, 601, DateTimeKind.Local).AddTicks(4233),
                            Email = "Pesho@biri.com",
                            IsBanned = false,
                            IsDeleted = false,
                            Password = "NaPeshoParolata",
                            RoleId = 1,
                            UserName = "Pesho"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.WishlistBeer", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "BeerId");

                    b.HasIndex("BeerId");

                    b.ToTable("WishlistBeers");
                });

            modelBuilder.Entity("BeerOverflow.Models.Beer", b =>
                {
                    b.HasOne("BeerOverflow.Models.Brewery", "Brewery")
                        .WithMany()
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Models.BeerType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Models.BeerDrank", b =>
                {
                    b.HasOne("BeerOverflow.Models.Beer", "Beer")
                        .WithMany()
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Models.User", "User")
                        .WithMany("BeersDrank")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Models.Brewery", b =>
                {
                    b.HasOne("BeerOverflow.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Models.Review", b =>
                {
                    b.HasOne("BeerOverflow.Models.User", "Author")
                        .WithMany("Reviews")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Models.Beer", "TargetBeer")
                        .WithMany("Reviews")
                        .HasForeignKey("TargetBeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Models.User", b =>
                {
                    b.HasOne("BeerOverflow.Models.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Models.WishlistBeer", b =>
                {
                    b.HasOne("BeerOverflow.Models.Beer", "Beer")
                        .WithMany()
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Models.User", "User")
                        .WithMany("Wishlist")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
